networks: {
  phoenix-network: {}
}

services:
  postgres:
    image: postgres:latest
    container_name: phoenix-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=phoenix
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phoenix-network
  phoenix-api:
    image: xen0xys/phoenix-api:latest
    container_name: phoenix-api
    ports:
      - "3000:3000"
    depends_on:
        postgres:
          condition: service_healthy
    environment:
      - NODE_ENV=production
      - DOTENV_KEY=${DOTENV_KEY}
      - DATABASE_URL=${DATABASE_URL}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 2
        window: 60s
    networks:
      - phoenix-network
