import {EncryptionService} from "../../src/services/encryption.service";

const encryptionService = new EncryptionService();
const todosEncryptionStrength = parseInt(process.env.TODOS_ENCRYPTION_STRENGTH);

export default (userSecret: string) => [
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Faire le ménage", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: "monthly",
        icon: "eye-slash",
        color: "blue",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Prendre un café", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        parent_id: 1,
        icon: "flask",
        color: "yellow",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Faire du jogging", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        parent_id: 1,
        icon: "eye-slash",
        color: "green",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Lire un livre", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        parent_id: 2,
        icon: "shopping-bag",
        color: "red",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Arroser les plantes", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        parent_id: 3,
        icon: "flask",
        color: "green",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Écouter de la musique", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        parent_id: 5,
        icon: "eye-slash",
        color: "blue",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Préparer le dîner", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: "daily",
        icon: "shopping-bag",
        color: "red",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Faire de l'exercice", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "flask",
        color: "yellow",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Planifier la semaine", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "eye-slash",
        color: "grey",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Faire une promenade", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "eye-slash",
        color: "green",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Regarder un film", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "eye-slash",
        color: "blue",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Faire du bénévolat", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "shopping-bag",
        color: "red",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Ranger la maison", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "flask",
        color: "yellow",
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        user_id: 1,
        name: encryptionService.encryptSymmetric("Écrire dans un journal", userSecret, todosEncryptionStrength),
        completed: false,
        deadline: new Date(),
        frequency: null,
        icon: "flask",
        color: "grey",
        created_at: new Date(),
        updated_at: new Date(),
    },
];
