name: Report a bug or suggest a feature
description: Allow you to report a bug or suggest a feature on the Phoenix-API !
body:
  - type: textarea
    attributes:
      label: Problem/Feature description
      description: Describe the problem you are facing or the feature you would like to see.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots and/or videos
      description: Add screenshots and/or videos illustrating the problem.
      placeholder: Drag and drop screenshots/videos into this box.
    validations:
      required: false
  - type: input
    attributes:
      label: Version
      description: Version used
    validations:
      required: true
